/* Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten
 * pentagonal numbers are:
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
 * 70 - 22 = 48, is not pentagonal.
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference
 * are pentagonal and D = |Pk - Pj| is minimised; what is the value of D? */

function prb44(){
  var limit = 2175,
      soluce = 0,
      p = [];
  
  for(var n = 0; n < limit; n++){
    p[n] = pentagonal(n);
  }
  
  for(var j = 1; j < limit; j++){
    for(var k = j; k < limit; k++){
      if(ispentagonal(p[k]+p[j])){
        if(ispentagonal(p[k]-p[j])){
          soluce = p[k]-p[j];
          break;
        }
      }
    }
    if(soluce!=0) break;
  }
  
  return soluce;
}
